#!/bin/bash
post_install() {
echo '
to use teiler you need to copy /usr/share/doc/teiler/config.example to $HOME/.config/teiler/config
Also copy /usr/share/doc/teiler/dmenurc to $HOME/.config/dmenurc

Install either dmenu2 or simpleswitcher-dd-git from AUR.
Then define a backend (dmenu or simpleswitcher) in $HOME/.config/dmenurc

You want to install some notification daemon. dunst is recommended.
'
} 
#post_install
